### ISSUE TITLE
Update Python/README.md

### ISSUE THREAD

**Issue by Dutta-SD** [Dutta-SD/sci-cpy#2]
`Python/README.md` - This is supposed to provide a brief outline about the python codes. 

Add to this README file

**Comment by Prashant0kgp** [comment]
@Dutta-SD, plz assign me,

**Comment by Dutta-SD** [comment]
Ok Assigning.
README.md should have little explanation regarding numerical methods in C, how one can use it etc.
Open a PR and add files in small increments. Mention this issue number.

**Comment by Dutta-SD** [comment]
Sure.
Go ahead and modify the `./Python/README.md` file and add your explanation.
I have already assigned this issue to you
