### ISSUE TITLE
Simpson's Rule Implementation

### ISSUE THREAD

**Issue by Dutta-SD** [Dutta-SD/sci-cpy#21]
Implement Simpson's rule for approximate integration.

Languages preferred : 

- [x] Python
- [x] C

**Comment by Dutta-SD** [comment]
#22 has implemented Simpson's rule in Python.
@yashdabhade1 you can add the code in C.

**Comment by yashdabhade1** [comment]
Yes Sure,
Can you please assign this issue to me

**Comment by Meghwantsingh** [comment]
Hello I also like to try this problem , But I am new to this can to tell what we have to in this problem.

**Comment by Dutta-SD** [comment]
Hi @Meghwantsingh 
Sorry, but code for this task has already been contributed.
I am closing this issue. Feel free to create a new issue and/or contribute to other issues.
