### ISSUE TITLE
Update C/README.md

### ISSUE THREAD

**Issue by Dutta-SD** [Dutta-SD/sci-cpy#3]
`C/README.md` - Brief summary about the C codes.

Add to this file

**Comment by Suraj-000** [comment]
Hello, please let me do it.

**Comment by Dutta-SD** [comment]
Ok @Suraj-000 Assigning it to you.
You don't need to write code. Just write about the algorithms in the proper file.

**Comment by Suraj-000** [comment]
Thank you @Dutta-SD. 
I wanted to know if i can contribute again and will it be counted on hacktoberfest.
Please let me know.
