### ISSUE TITLE
Create Python/Newton_Raphson

### ISSUE THREAD

**Issue by Dutta-SD** [Dutta-SD/sci-cpy#5]
Add Python Implementation of Newton Raphson method. 
- Add files as mentioned in CONTRIBUTING.md
- Links for reference : [YouTube](https://www.youtube.com/watch?v=szQUIRPrAgQ)

**Comment by ZenithFlux** [comment]
I've made a program on the method. Kindly review it and give feedback. #7 #7

**Comment by Dutta-SD** [comment]
Hi!
Let me review your PR and get back to you. Meanwhile, let me assign this issue to you.

**Comment by Dutta-SD** [comment]
Hi
Your code is awesome!
I have suggested one minor change in requirements.txt. Kindly add it and I will merge your pull request :smile:

**Comment by ZenithFlux** [comment]
Sorry I can't see your suggested change, did you suggest it in the pull request itself?

**Comment by Dutta-SD** [comment]
PR #7 
Yes, I suggested a small change over there only. At the end I have started a code review.

**Comment by Dutta-SD** [comment]
Done. Great Work!

**Comment by Dutta-SD** [comment]
Opening it for PR @ZenithFlux

**Comment by Dutta-SD** [comment]
Closing. This one done.
